
apiVersion: batch/v1beta1
kind: CronJob
metadata:
    labels:
      app: kube-hunter
      chart: kube-hunter-1.0.3
      heritage: self
      release: kube-hunter
    name: kube-hunter
    namespace: devsecops
spec:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:        
        annotations:
          #container.apparmor.security.beta.kubernetes.io/kube-hunter: runtime/default
          seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
        labels:
          app: kube-hunter
          release: kube-hunter
          heritage: self
          chart: kube-hunter-1.0.3
      spec:
        template:
          metadata:
            annotations:
              #container.apparmor.security.beta.kubernetes.io/kube-hunter: runtime/default
              seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
            labels:
              app: kube-hunter
              release: kube-hunter              
              #aadpodidbinding: devops-acr-poller-contridentity # this allows the pod to run as MI in Azure.
          spec:
            serviceAccountName: build-robot
            #nodeSelector:
                #poolname: largepool
            containers:
            - args: ["--pod", "--report", "json"]
              #- --pod
              
              command:
              - kube-hunter
              #- kube-hunter.py
              image: aquasec/kube-hunter
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: 250Mi
                  cpu: 250m
                requests:
                  memory: 100Mi
                  cpu: 25m
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsUser: 2102
                privileged: false
                readOnlyRootFilesystem: true
              name: kube-hunter
              resources: {}
            dnsPolicy: ClusterFirst
            restartPolicy: Never
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: '*/1440 * * * *' #should be */1440
    successfulJobsHistoryLimit: 1
    suspend: false
  