apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: defectdojo
  namespace: devsecops
spec:
    tls:
      - hosts:
        #- aws-defectdojo.cloudkube.xyz
        - metdojo.metricon.com.au
        secretName: ingress-secret-tls 
    rules:
    - host: metdojo.metricon.com.au
      http:
        paths:
        - backend:
            serviceName: defectdojo-django
            servicePort: 80
---
