apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: devops-addons
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: monitoring
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: qa
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: dev
automountServiceAccountToken: false
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: linkerd
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: ingress
automountServiceAccountToken: false
---
