
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-prod-admins
  namespace: prod
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prod-contributor-role-binding
  namespace: prod
subjects:
- kind: Group
  name: 76afa8ae-3b6c-4b53-bc36-43ddb4877cb9 #SID/objid of the Azure AD Group aks-prod-admins
  namespace: prod
roleRef:
  kind: Role
  name: aks-prod-admins
  apiGroup: rbac.authorization.k8s.io
---
