
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: Cluster-Admin-role-binding
subjects:
- kind: Group
  name: 3face878-a335-41c2-8121-b77759f7ff86 #SID of the Azure AD Group aks-dev-admins
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---


