apiVersion: v1
kind: Pod
metadata:
  name: dotnetcore-sample
  labels: 
   name: dotnetcore
  namespace: dev
  annotations: 
    linkerd.io/inject: disabled
  namespace: dev
spec:
  containers:
    - name: dotnetcore-sample    
      image: mcr.microsoft.com/dotnet/samples:aspnetapp
      securityContext:
        privileged: true
  serviceAccountName: build-robot
--- 


# This is a test pod to validate that the Azure Policy is flagging this pod.