apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: monitoring

  annotations:
    kubernetes.io/ingress.class: nginx   
spec:
    rules:
    - host: kibana.cloudkube.xyz
      http:
        paths:
        - backend:
            serviceName: kibana
            servicePort: 5601
---