apiVersion: v1
kind: Secret
metadata:
  name: voting-storage-secret
type: Opaque
data:
  MYSQL_USER: ZGJ1c2Vy  #dbuser(encoded ZGJ1c2Vy) is the actual change this(and encode) -- change this to dbuserdummy (ZABiAHUAcwBlAHIAZAB1AG0AbQB5AA==) test LOKI logs
  MYSQL_PASSWORD: UGFzc3dvcmQxMg==
  MYSQL_DATABASE: YXp1cmV2b3Rl  # YXp1cmV2b3Rl actual
  MYSQL_ROOT_PASSWORD: UGFzc3dvcmQxMg==