apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  #namespace: kube-logging
  namespace: kube-system
  labels:
    app: fluentd  
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      #in AKS we are setting this taint so that only kube-system pods run on this pool and NOT application pools.
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.7.3-debian-elasticsearch7-1.0        # fluentd-kubernetes-daemonset -- Over 100M docker downloads as of Nov 2020
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.monitoring.svc.cluster.local" 
          #for hosted elastic <fetech URL from elastic cloud> - for example 93716f3158134061b6db85442eb7b53c.australiaeast.azure.elastic-cloud.com
          #for Elastic running inside the cluster "elasticsearch.monitoring.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          #for hosted elastic <fetech port from elastic cloud> -- 9243s
          #for Elastic running inside the cluster "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "https"
          - name: FLUENTD_SYSTEMD_CONF
            value: disable
          - name: FLUENT_ELASTICSEARCH_SED_DISABLE
            value: "true"            
          - name: FLUENT_ELASTICSEARCH_USER
            value: "elastic" # The username you've set up for elasticsearch
          #Not required if Elastic is running inside k8s
          #- name: FLUENT_ELASTICSEARCH_PASSWORD
          #  value: "" # The password you've got for cloud elastic
          #Not required if Elastic is running inside k8s
          - name:  FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "false"
          #Not mandatory - just in case you are using self-signed cert.
          - name: FLUENT_ELASTICSEARCH_SSL_VERSION
            value: "TLSv1_2"                  
          #Required for cloud Elastic
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentconfig #disable if breaks
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        #- name: fluentconfig #disable if breaks
        #  mountPath: /fluentd/etc/kubernetes.conf
        #  subPath: kubernetes.conf  
        
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers          
      - name: fluentconfig #disable if breaks
        configMap:
          name: fluentd-configmap
      