grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
## grafana Authentication can be enabled with the following values on grafana.ini
  server:
      # The full public facing url you use in browser, used for redirects and emails
     root_url:  #EX: https://grafana.cloudkube.xyz/
  auth.azuread:
    name: Azure AD
    enabled: true
    allow_sign_up: true
    client_id: 
    client_secret: ''
    scopes: openid email profile
    auth_url: https://login.microsoftonline.com/5778ff5f-1d7d-4252-b467-0fa895e5475f/oauth2/v2.0/authorize
    token_url: https://login.microsoftonline.com/5778ff5f-1d7d-4252-b467-0fa895e5475f/oauth2/v2.0/token
    #allowed_domains: metricon.com.au
    #allowed_groups: a7f3744e-881d-4c51-80ec-b575da74fc96
    