apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels: 
    app: {{ .Values.serviceName }}
spec:
  ports:
  - port: {{ .Values.service.externalPort1 }}
    name: redis
    targetPort: {{ .Values.service.internalPort1 }}
  - port: {{ .Values.service.externalPort2 }}
    name: mysql
    targetPort: {{ .Values.service.internalPort2 }}
  selector:
    app: {{ .Values.deploymentName }}
---
