apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: defectdojo
  namespace: devops-addons
  annotations:
    kubernetes.io/ingress.class: nginx   
    nginx.ingress.kubernetes.io/proxy-body-size: "600m"
    nginx.org/client-max-body-size: "600m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
    tls:
      - hosts:
        - {{ .Values.host }} #dev-defectdojo.cloudkube.xyz -- should match SPN redirect URL.
        secretName: ingress-secret-tls 
    rules:
    - host: {{ .Values.host }} #dev-defectdojo.cloudkube.xyz -- should match SPN redirect URL.
      http:
        paths:
        - backend:
            serviceName: defectdojo-django
            servicePort: 80
---
